package dev.supirvast.vastir.preview;

import dev.supirvast.vastir.core.Builtin;
import dev.supirvast.vastir.core.BinaryOp;
import dev.supirvast.vastir.core.CoreModule;
import dev.supirvast.vastir.core.EntryPoint;
import dev.supirvast.vastir.core.Expr;
import dev.supirvast.vastir.core.Function;
import dev.supirvast.vastir.core.InterfaceVar;
import dev.supirvast.vastir.core.Region;
import dev.supirvast.vastir.core.ShaderStage;
import dev.supirvast.vastir.core.Statement;
import dev.supirvast.vastir.lower.CoreToSpirv;
import dev.supirvast.vastir.type.Type;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates the previewer's reproducible sample assets: a {@code cube.obj} and the {@code model.vert.spv} /
 * {@code model.frag.spv} pair authored in the {@code core} IR and lowered with {@link CoreToSpirv}. Run it once
 * to produce inputs for a real previewer run:
 *
 * <pre>java dev.supirvast.vastir.preview.SampleAssets &lt;outDir&gt;</pre>
 *
 * <p>The cube is generated <em>pre-rotated</em> and placed in valid Vulkan clip space (x,y in [-1,1], z in
 * [0,1]) so the static pipeline (no MVP yet) still shows multiple faces with distinct normals. The vertex
 * shader emits {@code gl_Position} straight from the model position and passes the normal through; the fragment
 * shader colors by {@code normal * 0.5 + 0.5}.
 */
public final class SampleAssets {

    private static final Type.Float F32 = Type.float32();
    private static final Type.Vector VEC3 = new Type.Vector(F32, 3);
    private static final Type.Vector VEC4 = new Type.Vector(F32, 4);

    private SampleAssets() {
    }

    public static void main(String[] args) {
        Path outDir = Path.of(args.length > 0 ? args[0] : "samples");
        try {
            Files.createDirectories(outDir);
            Files.writeString(outDir.resolve("cube.obj"), cubeObj());
            Files.writeString(outDir.resolve("cube.ply"), cubePly());
            Files.write(outDir.resolve("model.vert.spv"), vertexShader());
            Files.write(outDir.resolve("model.frag.spv"), fragmentShader());
        } catch (IOException e) {
            throw new UncheckedIOException("failed to write sample assets to " + outDir, e);
        }
        System.out.println("[sample-assets] wrote cube.obj, cube.ply, model.vert.spv, model.frag.spv to " + outDir);
    }

    // Six quad faces (1-based corner indices), one per cube side; PLY subtracts 1 for its 0-based indices.
    private static final int[][] FACES = {
            {1, 2, 3, 4}, {5, 6, 7, 8}, {1, 4, 8, 5}, {2, 3, 7, 6}, {1, 2, 6, 5}, {4, 3, 7, 8},
    };

    /** The eight cube corners, rotated so several faces are visible head-on, centered in clip space at z=0.5. */
    private static float[][] rotatedCorners() {
        float h = 0.25f;
        float ax = 0.5f;   // rotation about X
        float ay = 0.7f;   // rotation about Y
        float zCenter = 0.5f;
        float[][] corners = {
                {-h, -h, -h}, {h, -h, -h}, {h, h, -h}, {-h, h, -h},
                {-h, -h, h}, {h, -h, h}, {h, h, h}, {-h, h, h},
        };
        float[][] out = new float[corners.length][];
        for (int i = 0; i < corners.length; i++) {
            float[] r = rotate(corners[i], ax, ay);
            out[i] = new float[]{r[0], r[1], r[2] + zCenter};
        }
        return out;
    }

    /** The cube as a Wavefront OBJ (1-based faces, positions only — normals computed on load). */
    static String cubeObj() {
        float[][] corners = rotatedCorners();
        StringBuilder obj = new StringBuilder("# generated by SampleAssets — pre-rotated unit cube\n");
        for (float[] c : corners) {
            obj.append("v ").append(c[0]).append(' ').append(c[1]).append(' ').append(c[2]).append('\n');
        }
        for (int[] f : FACES) {
            obj.append("f ").append(f[0]).append(' ').append(f[1]).append(' ')
                    .append(f[2]).append(' ').append(f[3]).append('\n');
        }
        return obj.toString();
    }

    /** The same cube as ASCII PLY with per-vertex colors — exercises PLY's named channels (0-based faces). */
    static String cubePly() {
        float[][] corners = rotatedCorners();
        StringBuilder ply = new StringBuilder("""
                ply
                format ascii 1.0
                comment generated by SampleAssets — pre-rotated unit cube with vertex colors
                element vertex 8
                property float x
                property float y
                property float z
                property uchar red
                property uchar green
                property uchar blue
                element face 6
                property list uchar int vertex_indices
                end_header
                """);
        for (int i = 0; i < corners.length; i++) {
            float[] c = corners[i];
            // Eight distinct colors from the corner index, so the channels are visibly meaningful.
            int red = (i & 1) != 0 ? 255 : 40;
            int green = (i & 2) != 0 ? 255 : 40;
            int blue = (i & 4) != 0 ? 255 : 40;
            ply.append(c[0]).append(' ').append(c[1]).append(' ').append(c[2]).append(' ')
                    .append(red).append(' ').append(green).append(' ').append(blue).append('\n');
        }
        for (int[] f : FACES) {
            ply.append("4 ").append(f[0] - 1).append(' ').append(f[1] - 1).append(' ')
                    .append(f[2] - 1).append(' ').append(f[3] - 1).append('\n');
        }
        return ply.toString();
    }

    /** Rotate a point about X by {@code ax} then about Y by {@code ay} (length-preserving). */
    private static float[] rotate(float[] p, float ax, float ay) {
        float cx = (float) Math.cos(ax);
        float sx = (float) Math.sin(ax);
        float y = p[1] * cx - p[2] * sx;
        float z = p[1] * sx + p[2] * cx;
        float cy = (float) Math.cos(ay);
        float sy = (float) Math.sin(ay);
        float x = p[0] * cy + z * sy;
        float z2 = -p[0] * sy + z * cy;
        return new float[]{x, y, z2};
    }

    /** {@code gl_Position = vec4(position, 1.0); vNormal = normal;} */
    static byte[] vertexShader() {
        InterfaceVar position = InterfaceVar.input("position", 0, VEC3);
        InterfaceVar normal = InterfaceVar.input("normal", 1, VEC3);
        InterfaceVar vNormal = InterfaceVar.output("vNormal", 0, VEC3);
        Expr clip = new Expr.VectorConstruct(VEC4,
                List.of(new Expr.InterfaceRead(position), new Expr.ConstFloat(F32, 1.0)));
        Region body = Region.of(
                new Statement.BuiltinWrite(Builtin.POSITION, clip),
                new Statement.InterfaceWrite(vNormal, new Expr.InterfaceRead(normal)),
                new Statement.ReturnVoid());
        Function main = new Function("main", new Type.FunctionType(Type.VOID, List.of()), body);
        return new CoreToSpirv()
                .lower(new CoreModule().addEntryPoint(EntryPoint.of(main, ShaderStage.VERTEX)))
                .toByteArray();
    }

    /** {@code fragColor = vec4(vNormal * 0.5 + 0.5, 1.0);} — maps the [-1,1] normal into a [0,1] color. */
    static byte[] fragmentShader() {
        InterfaceVar vNormal = InterfaceVar.input("vNormal", 0, VEC3);
        InterfaceVar fragColor = InterfaceVar.output("fragColor", 0, VEC4);
        Expr half = new Expr.VectorConstruct(VEC3, List.of(
                new Expr.ConstFloat(F32, 0.5), new Expr.ConstFloat(F32, 0.5), new Expr.ConstFloat(F32, 0.5)));
        Expr scaled = new Expr.Binary(BinaryOp.MUL, new Expr.InterfaceRead(vNormal), half);
        Expr biased = new Expr.Binary(BinaryOp.ADD, scaled, half);
        Expr color = new Expr.VectorConstruct(VEC4, List.of(biased, new Expr.ConstFloat(F32, 1.0)));
        Region body = Region.of(
                new Statement.InterfaceWrite(fragColor, color),
                new Statement.ReturnVoid());
        Function main = new Function("main", new Type.FunctionType(Type.VOID, List.of()), body);
        return new CoreToSpirv()
                .lower(new CoreModule().addEntryPoint(EntryPoint.of(main, ShaderStage.FRAGMENT)))
                .toByteArray();
    }
}
