package dev.supirvast.vastir.preview;

import dev.supirvast.vastir.core.Builtin;
import dev.supirvast.vastir.core.BinaryOp;
import dev.supirvast.vastir.core.CoreModule;
import dev.supirvast.vastir.core.EntryPoint;
import dev.supirvast.vastir.core.Expr;
import dev.supirvast.vastir.core.Function;
import dev.supirvast.vastir.core.InterfaceVar;
import dev.supirvast.vastir.core.Region;
import dev.supirvast.vastir.core.ShaderStage;
import dev.supirvast.vastir.core.Statement;
import dev.supirvast.vastir.core.Texture;
import dev.supirvast.vastir.lower.CoreToSpirv;
import dev.supirvast.vastir.type.Type;
import org.lwjgl.system.MemoryUtil;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.lwjgl.stb.STBImageWrite.stbi_write_png;

/**
 * Generates the previewer's reproducible sample assets: a {@code cube.obj} and the {@code model.vert.spv} /
 * {@code model.frag.spv} pair authored in the {@code core} IR and lowered with {@link CoreToSpirv}. Run it once
 * to produce inputs for a real previewer run:
 *
 * <pre>java dev.supirvast.vastir.preview.SampleAssets &lt;outDir&gt;</pre>
 *
 * <p>The cube is generated <em>pre-rotated</em> and placed in valid Vulkan clip space (x,y in [-1,1], z in
 * [0,1]) so the static pipeline (no MVP yet) still shows multiple faces with distinct normals. The vertex
 * shader emits {@code gl_Position} straight from the model position and passes the normal through; the fragment
 * shader colors by {@code normal * 0.5 + 0.5}.
 */
public final class SampleAssets {

    private static final Type.Float F32 = Type.float32();
    private static final Type.Vector VEC2 = new Type.Vector(F32, 2);
    private static final Type.Vector VEC3 = new Type.Vector(F32, 3);
    private static final Type.Vector VEC4 = new Type.Vector(F32, 4);

    private SampleAssets() {
    }

    public static void main(String[] args) {
        Path outDir = Path.of(args.length > 0 ? args[0] : "samples");
        try {
            Files.createDirectories(outDir);
            Files.writeString(outDir.resolve("cube.obj"), cubeObj());
            Files.writeString(outDir.resolve("cube.ply"), cubePly());
            Files.write(outDir.resolve("model.vert.spv"), vertexShader());
            Files.write(outDir.resolve("model.frag.spv"), fragmentShader());
            // Textured sample: a UV quad, a checkerboard texture, and a shader that samples it.
            Files.writeString(outDir.resolve("quad.obj"), quadObj());
            Files.write(outDir.resolve("textured.vert.spv"), texturedVertexShader());
            Files.write(outDir.resolve("textured.frag.spv"), texturedFragmentShader());
            writeChecker(outDir.resolve("checker.png"));
            writeCubemap(outDir.resolve("env"));   // env_px.png … env_nz.png
        } catch (IOException e) {
            throw new UncheckedIOException("failed to write sample assets to " + outDir, e);
        }
        System.out.println("[sample-assets] wrote cube.obj, cube.ply, quad.obj, checker.png, env_*.png, and the "
                + "model/textured shaders to " + outDir);
    }

    /** A camera-facing unit quad in clip space with UVs spanning the full [0,1] range. */
    static String quadObj() {
        return """
                # generated by SampleAssets — UV quad
                v -0.6 -0.6 0.5
                v  0.6 -0.6 0.5
                v  0.6  0.6 0.5
                v -0.6  0.6 0.5
                vt 0 0
                vt 1 0
                vt 1 1
                vt 0 1
                f 1/1 2/2 3/3 4/4
                """;
    }

    /** {@code gl_Position = vec4(position, 1); vUv = uv;} — passes the texcoord through to the fragment stage. */
    static byte[] texturedVertexShader() {
        InterfaceVar position = InterfaceVar.input("position", 0, VEC3);
        InterfaceVar uv = InterfaceVar.input("uv", 2, VEC2);
        InterfaceVar vUv = InterfaceVar.output("vUv", 0, VEC2);
        Region body = Region.of(
                new Statement.BuiltinWrite(Builtin.POSITION, new Expr.VectorConstruct(VEC4,
                        List.of(new Expr.InterfaceRead(position), new Expr.ConstFloat(F32, 1.0)))),
                new Statement.InterfaceWrite(vUv, new Expr.InterfaceRead(uv)),
                new Statement.ReturnVoid());
        Function main = new Function("main", new Type.FunctionType(Type.VOID, List.of()), body);
        return new CoreToSpirv()
                .lower(new CoreModule().addEntryPoint(EntryPoint.of(main, ShaderStage.VERTEX)))
                .toByteArray();
    }

    /** {@code fragColor = texture(tex, vUv);} — samples the bound texture at descriptor set 0, binding 0. */
    static byte[] texturedFragmentShader() {
        Texture tex = new Texture("tex", 0, 0);
        InterfaceVar vUv = InterfaceVar.input("vUv", 0, VEC2);
        InterfaceVar fragColor = InterfaceVar.output("fragColor", 0, VEC4);
        Region body = Region.of(
                new Statement.InterfaceWrite(fragColor,
                        new Expr.SampleTexture(tex, new Expr.InterfaceRead(vUv))),
                new Statement.ReturnVoid());
        Function main = new Function("main", new Type.FunctionType(Type.VOID, List.of()), body);
        return new CoreToSpirv()
                .lower(new CoreModule().addEntryPoint(EntryPoint.of(main, ShaderStage.FRAGMENT)))
                .toByteArray();
    }

    /** Writes a 256×256 magenta/white checkerboard PNG (32px squares) for texturing tests. */
    static void writeChecker(Path path) {
        int size = 256;
        int square = 32;
        ByteBuffer pixels = MemoryUtil.memAlloc(size * size * 4);
        for (int y = 0; y < size; y++) {
            for (int x = 0; x < size; x++) {
                boolean light = (((x / square) + (y / square)) & 1) == 0;
                pixels.put((byte) (light ? 245 : 200))
                        .put((byte) (light ? 245 : 30))
                        .put((byte) (light ? 245 : 160))
                        .put((byte) 255);
            }
        }
        pixels.flip();
        boolean ok = stbi_write_png(path.toString(), size, size, 4, pixels, size * 4);
        MemoryUtil.memFree(pixels);
        if (!ok) {
            throw new IllegalStateException("stbi_write_png failed for " + path);
        }
    }

    /**
     * Writes six cubemap face PNGs ({@code <prefix>_px/_nx/_py/_ny/_pz/_nz.png}), one distinct color per face
     * (with a vertical gradient), so a reflective surface shows a clearly directional environment.
     */
    static void writeCubemap(Path prefix) {
        // Vulkan face order: +X, -X, +Y, -Y, +Z, -Z.
        int[] colors = {0xE03030, 0x30D0D0, 0xF0F0F0, 0x303048, 0x30C040, 0x3050E0};
        String[] suffixes = {"_px", "_nx", "_py", "_ny", "_pz", "_nz"};
        for (int f = 0; f < 6; f++) {
            writeFace(Path.of(prefix + suffixes[f] + ".png"), colors[f]);
        }
    }

    private static void writeFace(Path path, int rgb) {
        int size = 256;
        int r = (rgb >> 16) & 0xFF;
        int g = (rgb >> 8) & 0xFF;
        int bl = rgb & 0xFF;
        ByteBuffer pixels = MemoryUtil.memAlloc(size * size * 4);
        for (int y = 0; y < size; y++) {
            float t = 1.0f - 0.35f * y / size;   // brighten toward the top edge
            for (int x = 0; x < size; x++) {
                pixels.put((byte) (r * t)).put((byte) (g * t)).put((byte) (bl * t)).put((byte) 255);
            }
        }
        pixels.flip();
        boolean ok = stbi_write_png(path.toString(), size, size, 4, pixels, size * 4);
        MemoryUtil.memFree(pixels);
        if (!ok) {
            throw new IllegalStateException("stbi_write_png failed for " + path);
        }
    }

    // Six quad faces (1-based corner indices), one per cube side; PLY subtracts 1 for its 0-based indices.
    private static final int[][] FACES = {
            {1, 2, 3, 4}, {5, 6, 7, 8}, {1, 4, 8, 5}, {2, 3, 7, 6}, {1, 2, 6, 5}, {4, 3, 7, 8},
    };

    /** The eight cube corners, rotated so several faces are visible head-on, centered in clip space at z=0.5. */
    private static float[][] rotatedCorners() {
        float h = 0.25f;
        float ax = 0.5f;   // rotation about X
        float ay = 0.7f;   // rotation about Y
        float zCenter = 0.5f;
        float[][] corners = {
                {-h, -h, -h}, {h, -h, -h}, {h, h, -h}, {-h, h, -h},
                {-h, -h, h}, {h, -h, h}, {h, h, h}, {-h, h, h},
        };
        float[][] out = new float[corners.length][];
        for (int i = 0; i < corners.length; i++) {
            float[] r = rotate(corners[i], ax, ay);
            out[i] = new float[]{r[0], r[1], r[2] + zCenter};
        }
        return out;
    }

    /** The cube as a Wavefront OBJ (1-based faces, positions only — normals computed on load). */
    static String cubeObj() {
        float[][] corners = rotatedCorners();
        StringBuilder obj = new StringBuilder("# generated by SampleAssets — pre-rotated unit cube\n");
        for (float[] c : corners) {
            obj.append("v ").append(c[0]).append(' ').append(c[1]).append(' ').append(c[2]).append('\n');
        }
        for (int[] f : FACES) {
            obj.append("f ").append(f[0]).append(' ').append(f[1]).append(' ')
                    .append(f[2]).append(' ').append(f[3]).append('\n');
        }
        return obj.toString();
    }

    /** The same cube as ASCII PLY with per-vertex colors — exercises PLY's named channels (0-based faces). */
    static String cubePly() {
        float[][] corners = rotatedCorners();
        StringBuilder ply = new StringBuilder("""
                ply
                format ascii 1.0
                comment generated by SampleAssets — pre-rotated unit cube with vertex colors
                element vertex 8
                property float x
                property float y
                property float z
                property uchar red
                property uchar green
                property uchar blue
                element face 6
                property list uchar int vertex_indices
                end_header
                """);
        for (int i = 0; i < corners.length; i++) {
            float[] c = corners[i];
            // Eight distinct colors from the corner index, so the channels are visibly meaningful.
            int red = (i & 1) != 0 ? 255 : 40;
            int green = (i & 2) != 0 ? 255 : 40;
            int blue = (i & 4) != 0 ? 255 : 40;
            ply.append(c[0]).append(' ').append(c[1]).append(' ').append(c[2]).append(' ')
                    .append(red).append(' ').append(green).append(' ').append(blue).append('\n');
        }
        for (int[] f : FACES) {
            ply.append("4 ").append(f[0] - 1).append(' ').append(f[1] - 1).append(' ')
                    .append(f[2] - 1).append(' ').append(f[3] - 1).append('\n');
        }
        return ply.toString();
    }

    /** Rotate a point about X by {@code ax} then about Y by {@code ay} (length-preserving). */
    private static float[] rotate(float[] p, float ax, float ay) {
        float cx = (float) Math.cos(ax);
        float sx = (float) Math.sin(ax);
        float y = p[1] * cx - p[2] * sx;
        float z = p[1] * sx + p[2] * cx;
        float cy = (float) Math.cos(ay);
        float sy = (float) Math.sin(ay);
        float x = p[0] * cy + z * sy;
        float z2 = -p[0] * sy + z * cy;
        return new float[]{x, y, z2};
    }

    /** {@code gl_Position = vec4(position, 1.0); vNormal = normal;} */
    static byte[] vertexShader() {
        InterfaceVar position = InterfaceVar.input("position", 0, VEC3);
        InterfaceVar normal = InterfaceVar.input("normal", 1, VEC3);
        InterfaceVar vNormal = InterfaceVar.output("vNormal", 0, VEC3);
        Expr clip = new Expr.VectorConstruct(VEC4,
                List.of(new Expr.InterfaceRead(position), new Expr.ConstFloat(F32, 1.0)));
        Region body = Region.of(
                new Statement.BuiltinWrite(Builtin.POSITION, clip),
                new Statement.InterfaceWrite(vNormal, new Expr.InterfaceRead(normal)),
                new Statement.ReturnVoid());
        Function main = new Function("main", new Type.FunctionType(Type.VOID, List.of()), body);
        return new CoreToSpirv()
                .lower(new CoreModule().addEntryPoint(EntryPoint.of(main, ShaderStage.VERTEX)))
                .toByteArray();
    }

    /** {@code fragColor = vec4(vNormal * 0.5 + 0.5, 1.0);} — maps the [-1,1] normal into a [0,1] color. */
    static byte[] fragmentShader() {
        InterfaceVar vNormal = InterfaceVar.input("vNormal", 0, VEC3);
        InterfaceVar fragColor = InterfaceVar.output("fragColor", 0, VEC4);
        Expr half = new Expr.VectorConstruct(VEC3, List.of(
                new Expr.ConstFloat(F32, 0.5), new Expr.ConstFloat(F32, 0.5), new Expr.ConstFloat(F32, 0.5)));
        Expr scaled = new Expr.Binary(BinaryOp.MUL, new Expr.InterfaceRead(vNormal), half);
        Expr biased = new Expr.Binary(BinaryOp.ADD, scaled, half);
        Expr color = new Expr.VectorConstruct(VEC4, List.of(biased, new Expr.ConstFloat(F32, 1.0)));
        Region body = Region.of(
                new Statement.InterfaceWrite(fragColor, color),
                new Statement.ReturnVoid());
        Function main = new Function("main", new Type.FunctionType(Type.VOID, List.of()), body);
        return new CoreToSpirv()
                .lower(new CoreModule().addEntryPoint(EntryPoint.of(main, ShaderStage.FRAGMENT)))
                .toByteArray();
    }
}
