package dev.supirvast.vastir.codegen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Emits {@code Op.java}: the enum of all SPIR-V opcodes, each carrying its numeric opcode, instruction
 * class, introducing core version, provisional flag, and ordered operand layout.
 *
 * <p>Operand layout references the shared {@code OperandKind}/{@code Operand}/{@code Quantifier} types, so
 * an op's operands are typed references into the operand-kind enums rather than raw strings.
 */
final class OpEnumGenerator {

    private final Grammar grammar;

    OpEnumGenerator(Grammar grammar) {
        this.grammar = grammar;
    }

    /**
     * Max operand-bearing ops per generated init method. Each {@code put(...)} compiles to a few hundred
     * bytes; staying well under ~200 keeps every method comfortably below the JVM's 64 KB method limit.
     */
    private static final int OPERAND_CHUNK = 120;

    Path generateTo(Path outputRoot) throws IOException {
        StringBuilder out = new StringBuilder(256 * 1024);
        emitHeader(out);
        emitConstants(out);
        emitBody(out);
        emitOperandTable(out);
        out.append("}\n");
        Path file = SpirvCodegen.javaFile(outputRoot, "Op");
        Files.writeString(file, out.toString(), StandardCharsets.UTF_8);
        return file;
    }

    private void emitHeader(StringBuilder out) {
        out.append("package ").append(SpirvCodegen.GENERATED_PACKAGE).append(";\n\n");
        out.append("import java.util.EnumMap;\n");
        out.append("import java.util.HashMap;\n");
        out.append("import java.util.List;\n");
        out.append("import java.util.Map;\n");
        out.append("import java.util.Optional;\n\n");
        out.append("/**\n");
        out.append(" * GENERATED by vastir-codegen from the official SPIR-V grammar. DO NOT EDIT.\n");
        out.append(" *\n");
        out.append(" * <p>Source: KhronosGroup/SPIRV-Headers, spirv.core.grammar.json.\n");
        out.append(String.format(" * SPIR-V %s revision %d, magic %s.%n",
                grammar.spirvVersion(), grammar.revision, grammar.magicNumber));
        out.append(" */\n");
        out.append("public enum Op {\n");
    }

    private void emitConstants(StringBuilder out) {
        int n = grammar.instructions.size();
        for (int i = 0; i < n; i++) {
            Grammar.Instruction ins = grammar.instructions.get(i);
            out.append("    ").append(ins.opname).append('(')
                    .append(ins.opcode).append(", ")
                    .append(JavaSource.stringLiteral(ins.instructionClass)).append(", ")
                    .append(JavaSource.stringLiteral(ins.version)).append(", ")
                    .append(ins.provisional).append(')')
                    .append(i == n - 1 ? ";" : ",").append('\n');
        }
        out.append('\n');
    }

    private void emitBody(StringBuilder out) {
        out.append("""
                    private final int opcode;
                    private final String spirvClass;
                    private final String sinceVersion;
                    private final boolean provisional;

                    Op(int opcode, String spirvClass, String sinceVersion, boolean provisional) {
                        this.opcode = opcode;
                        this.spirvClass = spirvClass;
                        this.sinceVersion = sinceVersion;
                        this.provisional = provisional;
                    }

                    /** The 16-bit SPIR-V opcode number written to the binary word stream. */
                    public int opcode() { return opcode; }

                    /** Grouping class from the grammar, e.g. "Constant-Creation". */
                    public String spirvClass() { return spirvClass; }

                    /** Earliest core SPIR-V version introducing this op, e.g. "1.0"; null if extension-only. */
                    public String sinceVersion() { return sinceVersion; }

                    /** True for ops from unratified provisional extensions. */
                    public boolean provisional() { return provisional; }

                    /** Ordered operand layout for this op (empty for operandless ops). */
                    public List<Operand> operands() { return OperandTable.of(this); }

                    private static final Map<Integer, Op> BY_OPCODE;
                    static {
                        Map<Integer, Op> m = new HashMap<>();
                        for (Op op : values()) {
                            m.putIfAbsent(op.opcode, op); // aliases may share an opcode; first wins
                        }
                        BY_OPCODE = Map.copyOf(m);
                    }

                    /** Looks up an op by its numeric opcode, if known. */
                    public static Optional<Op> byOpcode(int opcode) {
                        return Optional.ofNullable(BY_OPCODE.get(opcode));
                    }
                """);
    }

    /**
     * Emits a lazily-initialized operand-layout table. Operand construction is split across chunked
     * {@code init*()} methods (and out of the enum {@code <clinit>}) to stay under the 64 KB method limit;
     * the table is only built when {@code operands()} is first called.
     */
    private void emitOperandTable(StringBuilder out) {
        List<Grammar.Instruction> withOperands = grammar.instructions.stream()
                .filter(ins -> ins.operands != null && !ins.operands.isEmpty())
                .toList();
        int chunks = (withOperands.size() + OPERAND_CHUNK - 1) / OPERAND_CHUNK;

        out.append("\n    private static final class OperandTable {\n");
        out.append("        private static final Map<Op, List<Operand>> MAP = new EnumMap<>(Op.class);\n\n");
        out.append("        static {\n");
        for (int c = 0; c < chunks; c++) {
            out.append("            init").append(c).append("();\n");
        }
        out.append("        }\n\n");
        out.append("        private static Operand o(OperandKind kind, String name, Quantifier quantifier) {\n");
        out.append("            return new Operand(kind, name, quantifier);\n");
        out.append("        }\n\n");

        for (int c = 0; c < chunks; c++) {
            out.append("        private static void init").append(c).append("() {\n");
            int start = c * OPERAND_CHUNK;
            int end = Math.min(start + OPERAND_CHUNK, withOperands.size());
            for (int i = start; i < end; i++) {
                Grammar.Instruction ins = withOperands.get(i);
                out.append("            MAP.put(").append(ins.opname).append(", List.of(");
                for (int j = 0; j < ins.operands.size(); j++) {
                    Grammar.Operand op = ins.operands.get(j);
                    if (j > 0) {
                        out.append(", ");
                    }
                    out.append("o(OperandKind.").append(JavaSource.identifier(op.kind)).append(", ")
                            .append(JavaSource.stringLiteral(op.name)).append(", ")
                            .append(JavaSource.quantifierExpr(op.quantifier)).append(')');
                }
                out.append("));\n");
            }
            out.append("        }\n\n");
        }

        out.append("        static List<Operand> of(Op op) {\n");
        out.append("            return MAP.getOrDefault(op, List.of());\n");
        out.append("        }\n");
        out.append("    }\n");
    }
}
