package dev.supirvast.vastir.codegen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Emits one Java enum per ValueEnum/BitEnum operand kind (e.g. {@code StorageClass}, {@code FunctionControl}).
 *
 * <p>Each constant carries its 32-bit grammar value — ValueEnum values are decimal ints, BitEnum values are
 * the grammar's hex bitmask literals (valid Java {@code int} literals as-is, including bit 31). Enumerants
 * that carry parameters (e.g. {@code ExecutionMode.LocalSize}) also carry their ordered {@link Grammar.Operand}
 * layout, so a parameterized enum value knows the operands that must follow it.
 */
final class OperandEnumGenerator {

    private final Grammar grammar;

    OperandEnumGenerator(Grammar grammar) {
        this.grammar = grammar;
    }

    List<Path> generateTo(Path outputRoot) throws IOException {
        List<Path> written = new ArrayList<>();
        for (Grammar.OperandKind kind : grammar.operandKinds) {
            if ("ValueEnum".equals(kind.category) || "BitEnum".equals(kind.category)) {
                written.add(generateKind(kind, outputRoot));
            }
        }
        return written;
    }

    private Path generateKind(Grammar.OperandKind kind, Path outputRoot) throws IOException {
        boolean hasParams = kind.enumerants.stream()
                .anyMatch(e -> e.parameters != null && !e.parameters.isEmpty());
        String type = JavaSource.identifier(kind.kind);

        StringBuilder out = new StringBuilder(16 * 1024);
        out.append("package ").append(SpirvCodegen.GENERATED_PACKAGE).append(";\n\n");
        out.append("import java.util.HashMap;\n");
        if (hasParams) {
            out.append("import java.util.List;\n");
        }
        out.append("import java.util.Map;\n");
        out.append("import java.util.Optional;\n\n");
        out.append("/** GENERATED by vastir-codegen from the official SPIR-V grammar. DO NOT EDIT.\n")
                .append(" *\n * <p>SPIR-V ").append(kind.category).append(" operand kind {@code ")
                .append(kind.kind).append("}.\n */\n");
        out.append("public enum ").append(type).append(" {\n");

        emitConstants(out, kind, hasParams);
        emitBody(out, type, hasParams);
        out.append("}\n");

        Path file = SpirvCodegen.javaFile(outputRoot, type);
        Files.writeString(file, out.toString(), StandardCharsets.UTF_8);
        return file;
    }

    private void emitConstants(StringBuilder out, Grammar.OperandKind kind, boolean hasParams) {
        int n = kind.enumerants.size();
        for (int i = 0; i < n; i++) {
            Grammar.Enumerant e = kind.enumerants.get(i);
            String name = JavaSource.identifier(e.enumerant);
            out.append("    ").append(name).append('(').append(valueLiteral(e.value));
            if (hasParams && e.parameters != null) {
                for (Grammar.Operand p : e.parameters) {
                    out.append(", p(OperandKind.").append(JavaSource.identifier(p.kind)).append(", ")
                            .append(JavaSource.stringLiteral(p.name)).append(", ")
                            .append(JavaSource.quantifierExpr(p.quantifier)).append(')');
                }
            }
            out.append(')').append(i == n - 1 ? ";" : ",");
            if (!name.equals(e.enumerant)) {
                out.append("  // spirv: ").append(e.enumerant);
            }
            out.append('\n');
        }
        out.append('\n');
    }

    private void emitBody(StringBuilder out, String type, boolean hasParams) {
        out.append("    private final int value;\n");
        if (hasParams) {
            out.append("    private final List<Operand> parameters;\n");
        }
        out.append('\n');

        if (hasParams) {
            out.append("    ").append(type).append("(int value, Operand... parameters) {\n");
            out.append("        this.value = value;\n");
            out.append("        this.parameters = List.of(parameters);\n");
            out.append("    }\n\n");
        } else {
            out.append("    ").append(type).append("(int value) {\n");
            out.append("        this.value = value;\n");
            out.append("    }\n\n");
        }

        out.append("    /** The 32-bit grammar value (enum constant for ValueEnum, bit mask for BitEnum). */\n");
        out.append("    public int value() { return value; }\n\n");

        if (hasParams) {
            out.append("    /** Operands that follow this value when it is used (empty if none). */\n");
            out.append("    public List<Operand> parameters() { return parameters; }\n\n");
            out.append("    private static Operand p(OperandKind kind, String name, Quantifier quantifier) {\n");
            out.append("        return new Operand(kind, name, quantifier);\n");
            out.append("    }\n\n");
        }

        out.append("    private static final Map<Integer, ").append(type).append("> BY_VALUE;\n");
        out.append("    static {\n");
        out.append("        Map<Integer, ").append(type).append("> m = new HashMap<>();\n");
        out.append("        for (").append(type).append(" e : values()) {\n");
        out.append("            m.putIfAbsent(e.value, e); // aliases may share a value; first wins\n");
        out.append("        }\n");
        out.append("        BY_VALUE = Map.copyOf(m);\n");
        out.append("    }\n\n");
        out.append("    /** Looks up a constant by its numeric value, if defined. */\n");
        out.append("    public static Optional<").append(type).append("> byValue(int value) {\n");
        out.append("        return Optional.ofNullable(BY_VALUE.get(value));\n");
        out.append("    }\n");
    }

    /**
     * Renders an enumerant value as a Java {@code int} literal. ValueEnum values arrive as JSON numbers
     * (Gson {@code Double}); BitEnum values arrive as hex strings (e.g. {@code "0x0002"}) that are already
     * valid Java int literals.
     */
    private static String valueLiteral(Object value) {
        if (value instanceof String s) {
            return s;
        }
        if (value instanceof Number num) {
            return Long.toString(num.longValue());
        }
        throw new IllegalArgumentException("unexpected enumerant value: " + value);
    }
}
