package dev.supirvast.vastir.codegen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Emits the small shared vocabulary that the other generated types build on:
 * {@code Quantifier}, the {@code Operand} record, and the {@code OperandKind} enum (all 71 operand kinds
 * with their category). These let {@code Op} and the per-kind enums reference operand kinds by type rather
 * than by raw string.
 */
final class SharedTypesGenerator {

    private static final String HEADER =
            "GENERATED by vastir-codegen from the official SPIR-V grammar. DO NOT EDIT.";

    private final Grammar grammar;

    SharedTypesGenerator(Grammar grammar) {
        this.grammar = grammar;
    }

    List<Path> generateTo(Path outputRoot) throws IOException {
        List<Path> written = new ArrayList<>();
        written.add(write(outputRoot, "Spirv", spirvConstants()));
        written.add(write(outputRoot, "Quantifier", quantifier()));
        written.add(write(outputRoot, "Operand", operand()));
        written.add(write(outputRoot, "OperandKind", operandKind()));
        return written;
    }

    private String spirvConstants() {
        return """
                package %s;

                /** %s
                 *
                 * <p>Module-level constants for the SPIR-V binary format.
                 */
                public final class Spirv {

                    private Spirv() {}

                    /** SPIR-V magic number, the first word of every module. */
                    public static final int MAGIC_NUMBER = %s;

                    public static final int MAJOR_VERSION = %d;
                    public static final int MINOR_VERSION = %d;

                    /** Header version word: {@code 0 | major << 16 | minor << 8 | 0}. */
                    public static final int VERSION_WORD = (MAJOR_VERSION << 16) | (MINOR_VERSION << 8);
                }
                """.formatted(SpirvCodegen.GENERATED_PACKAGE, HEADER,
                grammar.magicNumber, grammar.majorVersion, grammar.minorVersion);
    }

    private String quantifier() {
        return """
                package %s;

                /** %s */
                public enum Quantifier {
                    /** Exactly one operand. */
                    REQUIRED,
                    /** Zero or one operand. */
                    OPTIONAL,
                    /** Zero or more operands (always the trailing operand). */
                    VARIADIC
                }
                """.formatted(SpirvCodegen.GENERATED_PACKAGE, HEADER);
    }

    private String operand() {
        return """
                package %s;

                /**
                 * %s
                 *
                 * <p>One positional operand slot: the operand kind it accepts, an optional descriptive name
                 * from the grammar, and its arity.
                 */
                public record Operand(OperandKind kind, String name, Quantifier quantifier) {}
                """.formatted(SpirvCodegen.GENERATED_PACKAGE, HEADER);
    }

    private String operandKind() {
        StringBuilder out = new StringBuilder(8 * 1024);
        out.append("package ").append(SpirvCodegen.GENERATED_PACKAGE).append(";\n\n");
        out.append("/** ").append(HEADER).append("\n *\n")
                .append(" * <p>Every operand kind referenced by an instruction or enumerant parameter.\n */\n");
        out.append("public enum OperandKind {\n");
        List<Grammar.OperandKind> kinds = grammar.operandKinds;
        for (int i = 0; i < kinds.size(); i++) {
            Grammar.OperandKind k = kinds.get(i);
            out.append("    ").append(JavaSource.identifier(k.kind))
                    .append("(Category.").append(category(k.category)).append(')')
                    .append(i == kinds.size() - 1 ? ";" : ",").append('\n');
        }
        out.append("""

                    /** The structural family an operand kind belongs to. */
                    public enum Category { VALUE_ENUM, BIT_ENUM, LITERAL, ID, COMPOSITE }

                    private final Category category;

                    OperandKind(Category category) {
                        this.category = category;
                    }

                    /** Whether this kind is a closed enum, bitmask, literal, id, or composite. */
                    public Category category() { return category; }
                }
                """);
        return out.toString();
    }

    private static String category(String grammarCategory) {
        return switch (grammarCategory) {
            case "ValueEnum" -> "VALUE_ENUM";
            case "BitEnum" -> "BIT_ENUM";
            case "Literal" -> "LITERAL";
            case "Id" -> "ID";
            case "Composite" -> "COMPOSITE";
            default -> throw new IllegalArgumentException("unknown operand category: " + grammarCategory);
        };
    }

    private static Path write(Path outputRoot, String simpleName, String content) throws IOException {
        Path file = SpirvCodegen.javaFile(outputRoot, simpleName);
        Files.writeString(file, content, StandardCharsets.UTF_8);
        return file;
    }
}
